# Generated by Django 5.2.8 on 2025-11-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('kota', models.CharField(max_length=100)),
                ('no_telepon', models.CharField(max_length=100)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resi', models.CharField(max_length=100, unique=True)),
                ('penerima', models.CharField(max_length=100)),
                ('alamat_tujuan', models.TextField()),
                ('layanan', models.CharField(choices=[('REG', 'Reguler'), ('EXP', 'Express'), ('CARGO', 'Kargo')], default='REG', max_length=10)),
                ('berat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
                ('pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paket_dikirim', to='gogo.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DITERIMA', 'Paket diterima di agen'), ('DIKIRIM', 'Sedang dikirim'), ('SAMPAI', 'Telah sampai tujuan')], default='DITERIMA', max_length=30)),
                ('lokasi', models.CharField(max_length=100)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='gogo.paket')),
            ],
        ),
    ]
