# Generated by Django 5.2.8 on 2025-11-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paket',
            name='layanan',
            field=models.CharField(choices=[('REG', 'Reguler (2-3 Hari)'), ('EXP', 'Express (1 Hari)'), ('CARGO', 'Kargo (Min 10kg)')], default='REG', max_length=10),
        ),
        migrations.AlterField(
            model_name='paket',
            name='resi',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('DITERIMA', 'Paket Masuk ke Counter'), ('DIKIRIM', 'Sedang dalam Perjalanan'), ('SAMPAI', 'Paket Telah Diterima')], default='DITERIMA', max_length=30),
        ),
    ]
